backend:
  name: git-gateway
  branch: staging

media_folder: static/img
public_folder: /img

collections:
  - name: 'posts'
    label: 'Posts'
    format: 'json'
    folder: 'content/post'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Slug', name: 'slug', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'datetime' }
      - { label: 'Short', name: 'short', widget: 'text' }
      - { label: 'Feature', name: 'feature', widget: 'file' }
      - {label: "Tags",
        name: "tags",
        widget: "select",
        multiple: true,
        options: ["code", "comments", "startup"]}
      - { label: 'Body', name: 'body', widget: 'markdown' }
